### ISSUE TITLE
ExpiredJwtException

### ISSUE THREAD

**Issue by Samyssmile** [murraco/spring-boot-jwt#1]
Hi,  i tested your code, my problem ist that after tomcat started i have something about 20 sec to test API via Swagger, after ~20 sec  i got this: ExpiredJwtException

I dont understand why, because in your code i found: validityInMilliseconds  == 1 h.

can you reproduce the problem?

**Comment by murraco** [comment]
Sorry for the late response, I have been extremely busy. What you found in the code is this:

```java
@Value("${security.jwt.token.expire-length:3600000}")
private long validityInMilliseconds = 3600000; // 1h
```

`@Value` is reading the value `security.jwt.token.expire-length` from the `application.yml` file, or if it doesn't exist, setting the validity in milliseconds to 3600000 = 1h. You should change the value of `security.jwt.token.expire-length` from 3600 milliseconds to whatever you want/need it to be.
