### ISSUE TITLE
Needs @EnableWebSecurity?

### ISSUE THREAD

**Issue by ellispritchard** [murraco/spring-boot-jwt#10]
Without the addition of a `@EnableWebSecurity` annotation, the `WebSecurityConfig` class is never called.

https://github.com/murraco/spring-boot-jwt/blob/fc19d48a32fd241a11778eeeef922e150c3de0b1/src/main/java/murraco/security/WebSecurityConfig.java#L15

org.springframework.boot:spring-boot-starter-security:2.1.1-RELEASE
```

**Comment by murraco** [comment]
I see, good catch, I'm a bit outdated in terms of Spring Boot in general. I'll add this asap.
