### ISSUE TITLE
required a bean of type 'org.springframework.security.authentication.AuthenticationManager' that could not be found.

### ISSUE THREAD

**Issue by VEMTK** [murraco/spring-boot-jwt#14]
thanks

**Comment by murraco** [comment]
You should be more specific when opening an issue. When is this error being displayed? What version of Java are you using? Did you follow the [How to use this code?](https://github.com/murraco/spring-boot-jwt#how-to-use-this-code) section on the `README.md` file? Please add more details if you want me to help you.
