### ISSUE TITLE
AccessDeniedException

### ISSUE THREAD

**Issue by le-cardinal** [murraco/spring-boot-jwt#23]
Hi,

getting a DeniedException from Swagger doc:

token: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjbGllbnQiLCJhdXRoIjpbeyJhdXRob3JpdHkiOiJST0xFX0NMSUVOVCJ9XSwiaWF0IjoxNjEzNjM2NjAwLCJleHAiOjE2MTM2MzY5MDB9.JKxNcdaHL8tUQ4-s9SBweP6mGXabilHfVbP_dcxJKG4password: username: org.springframework.security.core.userdetails.User@af12f3cb: Username: client; Password: [PROTECTED]; Enabled: true; AccountNonExpired: true; credentialsNonExpired: true; AccountNonLocked: true; Granted Authorities: ROLE_CLIENT2021-02-18 09:23:33.493  WARN 20332 --- [nio-8080-exec-2] .m.m.a.ExceptionHandlerExceptionResolver : Resolved [org.springframework.security.access.AccessDeniedException: AccΦs refusΘ]

Any advice on that ?

Regards

**Comment by ramazansakin** [comment]
Hi @le-cardinal,

How do you reach swagger ui site? I m trying to reach http://localhost:8080/swagger-ui.html , and then no error on site.
By the way, there is no need to get token for swagger-ui.

Best Regards
