### ISSUE TITLE
This is not standard to not use authController

### ISSUE THREAD

**Issue by djassie** [murraco/spring-boot-jwt#29]
I checked this repo being good reputation. 

But conventionally most the Spring Security is using `authController` for authentication, and `userController` for accessing the data. 

But all logic crammed in same place is not good practice. 

One should always follow convention, because Open Source examples are being used in Live Projects.

**Comment by murraco** [comment]
🤔

**Comment by maxymapp** [comment]
> I checked this repo being good reputation.
> 
> But conventionally most the Spring Security is using `authController` for authentication, and `userController` for accessing the data.
> 
> But all logic crammed in same place is not good practice.
> 
> One should always follow convention, because Open Source examples are being used in Live Projects.

Don't be picky about controller name in this case. And don't be hard on the author. This is just an example for learning purposes. Thankful to the author for sharing this mini project. Good developer is smart enough to not use "open source examples" in "live projects" [read: production projects]  and write his own auth ! :)
