### ISSUE TITLE
Question about code: Why is clearing the context important?

### ISSUE THREAD

**Issue by JanDevDE** [murraco/spring-boot-jwt#9]
Hey,

just a quick question on why clearing the context (JwtTokenFilter, 38) is important?! 
-> If the token is wrong the authentication won't be set anyway because it will throw an exception, so why do we need to clear the context then?

**Comment by murraco** [comment]
Hi @JanDevDE, the reason is the same one stated in the comment on the line 37 of `JwtTokenFilter`, it is very important, since it guarantees the user is not authenticated at all. Is more to prevent than anything else.
